/**
 * Parse a TLS alert message
 */
export declare function parseTlsAlert(buffer: Uint8Array): {
    level: "WARNING" | "FATAL";
    description: "CLOSE_NOTIFY" | "UNEXPECTED_MESSAGE" | "BAD_RECORD_MAC" | "RECORD_OVERFLOW" | "HANDSHAKE_FAILURE" | "BAD_CERTIFICATE" | "UNSUPPORTED_CERTIFICATE" | "CERTIFICATE_REVOKED" | "CERTIFICATE_EXPIRED" | "CERTIFICATE_UNKNOWN" | "ILLEGAL_PARAMETER" | "UNKNOWN_CA" | "ACCESS_DENIED" | "DECODE_ERROR" | "DECRYPT_ERROR" | "PROTOCOL_VERSION" | "INSUFFICIENT_SECURITY" | "INTERNAL_ERROR" | "INAPPROPRIATE_FALLBACK" | "USER_CANCELED" | "MISSING_EXTENSION" | "UNSUPPORTED_EXTENSION" | "UNRECOGNIZED_NAME" | "BAD_CERTIFICATE_STATUS_RESPONSE" | "UNKNOWN_PSK_IDENTITY" | "CERTIFICATE_REQUIRED" | "NO_APPLICATION_PROTOCOL" | "DECRYPTION_FAILED_RESERVED" | "DECOMPRESSION_FAILURE" | "NO_CERTIFICATE_RESERVED" | "EXPORT_RESTRICTION_RESERVED" | "NO_RENEGOTIATION";
};
